language: node_js
node_js:
  - "11"
before_install:
  - "npm config set spin false"
install:
  - yarn install
script:


cache:
  yarn: true
  directories:
    - node_modules

deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: develop

